[paths]
proc_data = "/mnt/datasets/processed/SpeechSplit2"
raw_data = "/mnt/datasets/raw"

[options]
run_tests = ["train"]
trace = false
bottleneck = "large"
experiment = "trainmod"
ntfy_url = "https://ntfy.sh/oliverpatterson-speechsplit2"

[log]
level = "DEBUG"
file = true
