[paths]
proc_data = "/mnt/datasets/processed/SpeechSplit2"
raw_data = "/mnt/datasets/raw"
artefacts = "artefacts/scratch"

[options]
bottleneck = "large"
experiment = "scratch"
ntfy_url = "https://ntfy.sh/oliverpatterson-speechsplit2"
trace = false

[log]
level = "TRACE"
file = true
