[options]
run_tests = ["train"]
dataset_name = "vctk"
num_iters = 1600000
log_step = 100
train = true
return_latents = false
regenerate_data = false

[dataloader]
shuffle = true
batch_size = 24
num_workers = 24
samplier = 24

[training]
lr = 0.0001
beta1 = 0.9
beta2 = 0.999

[model]
freq_1 = 1
freq_2 = 1
freq_3 = 1
dim_neck_1 = 32
dim_neck_2 = 32
dim_neck_3 = 32
dim_enc = 512
dim_enc_2 = 128
dim_enc_3 = 256
dim_rhy = 80
dim_con = 80
dim_pit = 257
dim_freq = 80
dim_spk_emb = 82
dim_f0 = 257
dim_dec = 512
len_raw = 128
chs_grp = 16
min_len_seg = 19
max_len_seg = 32
min_len_seq = 64
max_len_seq = 128
max_len_pad = 192
dropout = 0.2
